services:
  - type: web
    name: online-voting-management-system
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        scope: RUNNER
